### ISSUE TITLE
Excitation voltage

### ISSUE THREAD

**Issue by tomhaber** [szbeni/forcegauge#1]
What kind of load cell are you using? Am I correct that since R20=20k and R21=8k2, the excitation voltage as well as AVDD will be 1.75V? What is the rated output of your load cell?

Thanks in advance

**Comment by szbeni** [comment]
Hi! 
EDITED.

The values are correct. I added the calculation to the schematic.
The excitation voltage is about 4.3V.
R20 = 20k
R21 = 8k2
VBG=1.25V
AVDD=VBG*(R20+R21)/R20 =1.25* ((20000+8200)/8200)  =>  4.3V

**Comment by szbeni** [comment]
Updated the schematic with the calculation. 
The loadcells I am using:
https://www.aliexpress.com/item/1005002046379393.html?spm=a2g0o.order_list.order_list_main.87.21ef1802pDKxhM

Rated output: 2mV/V
So it would give 8.6mV at full scale with 4.3V excitation.
